server.port=8080
ai.demo.mode=true

openai.api.key=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
openai.model=gpt-4o-mini
