package com.gobile.ai.service;

import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfWriter;

import org.springframework.stereotype.Service;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;

@Service
public class PdfService {

    public ByteArrayInputStream generatePdf(
            String titleText,
            String documentText
    ) {

        Document document = new Document(
                PageSize.A4,
                50,
                50,
                50,
                50
        );

        ByteArrayOutputStream out =
                new ByteArrayOutputStream();

        try {

            PdfWriter.getInstance(document, out);

            document.open();

            // =====================================
            // LAW FIRM NAME
            // =====================================

            Font firmFont = new Font(
                    Font.HELVETICA,
                    20,
                    Font.BOLD
            );

            Paragraph firmName = new Paragraph(
                    "GOBILE & ASSOCIATES INC.",
                    firmFont
            );

            firmName.setAlignment(Element.ALIGN_CENTER);

            document.add(firmName);

            // =====================================
            // PRACTICE TAGLINE
            // =====================================

            Font subFont = new Font(
                    Font.HELVETICA,
                    10,
                    Font.ITALIC
            );

            Paragraph subHeading = new Paragraph(
                    "AI-Powered Legal Drafting Platform",
                    subFont
            );

            subHeading.setAlignment(Element.ALIGN_CENTER);

            document.add(subHeading);

            document.add(Chunk.NEWLINE);

            // =====================================
            // DOCUMENT TITLE
            // =====================================

            Font titleFont = new Font(
                    Font.HELVETICA,
                    16,
                    Font.BOLD
            );

            Paragraph title = new Paragraph(
                    titleText.toUpperCase(),
                    titleFont
            );

            title.setAlignment(Element.ALIGN_CENTER);

            document.add(title);

            document.add(Chunk.NEWLINE);

            // =====================================
            // BODY
            // =====================================

            Font bodyFont = new Font(
                    Font.COURIER,
                    11,
                    Font.NORMAL
            );

            Paragraph body = new Paragraph(
                    documentText,
                    bodyFont
            );

            body.setAlignment(Element.ALIGN_LEFT);

            document.add(body);

            document.add(Chunk.NEWLINE);

            // =====================================
            // FOOTER
            // =====================================

            Font footerFont = new Font(
                    Font.HELVETICA,
                    9,
                    Font.ITALIC
            );

            Paragraph footer = new Paragraph(
                    "Generated by Gobile AI Legal Assistant",
                    footerFont
            );

            footer.setAlignment(Element.ALIGN_CENTER);

            document.add(footer);

            document.close();

        } catch (Exception e) {

            e.printStackTrace();
        }

        return new ByteArrayInputStream(
                out.toByteArray()
        );
    }
}